// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuTavUNGT1AIltOK5JU2H4WRSFrfoHgNk',
    appId: '1:445075221076:web:363552f24e1828aa0cdbc1',
    messagingSenderId: '445075221076',
    projectId: 'just-talk-d97a9',
    authDomain: 'just-talk-d97a9.firebaseapp.com',
    storageBucket: 'just-talk-d97a9.firebasestorage.app',
    measurementId: 'G-PQ38PTC6BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdKyxW3F0glrw3P8ZaLU6w0_2s51NDwes',
    appId: '1:445075221076:android:97aeb790e9b3dde90cdbc1',
    messagingSenderId: '445075221076',
    projectId: 'just-talk-d97a9',
    storageBucket: 'just-talk-d97a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnLKDrGVGczKYETnkclfNpxVfKHUfGPQM',
    appId: '1:445075221076:ios:2f571d9afb4386ae0cdbc1',
    messagingSenderId: '445075221076',
    projectId: 'just-talk-d97a9',
    storageBucket: 'just-talk-d97a9.firebasestorage.app',
    iosBundleId: 'com.example.justTalk',
  );
}
